# Generated by Django 6.0.6 on 2026-06-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('watchlist', models.ManyToManyField(to='core.profile')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('PERM_FOUNDER', models.BooleanField()),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
                ('roles', models.ManyToManyField(to='wiki.role')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.page')),
                ('tags', models.ManyToManyField(to='wiki.tag')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(to='wiki.tag'),
        ),
    ]
