# Generated by Django 6.0.6 on 2026-06-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_member_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='wiki',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
