# Generated by Django 6.0.6 on 2026-06-22 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_role_wiki_delete_member_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\-\\s]+$', 'Invalid page name.')]),
        ),
    ]
