# Generated by Django 6.0.6 on 2026-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_page_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='content',
            new_name='content_after',
        ),
        migrations.AddField(
            model_name='revision',
            name='content_before',
            field=models.TextField(null=True),
        ),
    ]
