# Generated by Django 6.0.6 on 2026-06-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_rename_content_revision_content_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.page'),
        ),
    ]
