services:
  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: ren_db_container
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${REN_DB_USER}
      POSTGRES_PASSWORD: ${REN_DB_PASSWORD}
      POSTGRES_DB: ${REN_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${REN_DB_USER} -d ${REN_DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    container_name: frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_db: