services:
  server:
    build:
      dockerfile: server/Dockerfile
      context: .
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./server:/app/server:Z
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: ren_db_container
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${REN_DB_USER}
      POSTGRES_PASSWORD: ${REN_DB_PASSWORD}
      POSTGRES_DB: ${REN_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${REN_DB_USER} -d ${REN_DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  client:
    build:
      dockerfile: client/Dockerfile
      context: .
    container_name: client
    volumes:
      - ./client:/app:Z
      - /app/node_modules
    ports:
      - "4200:4200"
      - "49153:49153"
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app

volumes:
  postgres_db:
