# Generated by Django 6.0.6 on 2026-07-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Test', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
