# Generated by Django 6.0.6 on 2026-06-20 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wiki_subdomain_role_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='subdomain',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9a-z\\-]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
    ]
