# Generated by Django 6.0.6 on 2026-07-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_friends_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('PERM_FOUNDER', models.BooleanField()),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
                ('roles', models.ManyToManyField(to='core.role')),
            ],
        ),
    ]
