# Generated by Django 6.0.6 on 2026-07-04 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_role_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='subdomain',
            field=models.CharField(error_messages={'unique': 'This subdomain is already taken.'}, max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z\\-]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
    ]
