# Generated by Django 6.0.6 on 2026-07-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_wiki_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='PERM_FOUNDER',
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField()),
                ('CREATE_PAGE', models.BooleanField(default=False)),
                ('READ_PAGE', models.BooleanField(default=False)),
                ('UPDATE_PAGE', models.BooleanField(default=False)),
                ('DELETE_PAGE', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
    ]
