# Generated by Django 6.0.6 on 2026-08-16 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_role_perm_founder_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\_\\.]*$', 'Only alphanumeric characters, underscores and periods are allowed.')]),
        ),
    ]
