# Generated by Django 6.0.6 on 2026-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='subdomain',
            field=models.CharField(default='first', max_length=25),
            preserve_default=False,
        ),
    ]
