# Generated by Django 6.0.6 on 2026-06-20 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wiki_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='subdomain',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('PERM_FOUNDER', models.BooleanField()),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
                ('roles', models.ManyToManyField(to='core.role')),
            ],
        ),
    ]
