# Generated by Django 6.0.6 on 2026-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_page_tags_alter_page_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
