# Generated by Django 6.0.6 on 2026-06-23 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_revision_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='content_after',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='content_before',
        ),
        migrations.AlterField(
            model_name='revision',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.page'),
        ),
    ]
