# Generated by Django 6.0.6 on 2026-06-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='No title', max_length=25),
            preserve_default=False,
        ),
    ]
