# Generated by Django 6.0.6 on 2026-06-22 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[\\w\\-\\s]+$', 'Invalid page name.')]),
        ),
    ]
